"model_deployments":
- "name": "local/qwen3-5-9b"
  "model_name": "local/qwen3-5-9b"
  "tokenizer_name": "qwen/qwen3.5-9b"
  "max_sequence_length": !!int "262144"
  "client_spec":
    "class_name": "helm.clients.openai_client.OpenAIClient"
    "args":
      "api_key": "lm-studio"
      "org_id": ""
      "base_url": "http://127.0.0.1:1234/v1"
- "name": "fireworks/kimi-k2p5"
  "model_name": "fireworks/kimi-k2p5"
  "tokenizer_name": "moonshot/kimi-k2p5"
  "max_sequence_length": !!int "131072"
  "client_spec":
    "class_name": "fireworks_client.FireworksNoThinkingClient"
    "args":
      "base_url": "https://api.fireworks.ai/inference/v1"
      "openai_model_name": "accounts/fireworks/models/kimi-k2p5"
      "system_prompt": ""
- "name": "fireworks/deepseek3_2"
  "model_name": "fireworks/deepseek3_2"
  "tokenizer_name": "deepseek3_2_tokenizer"
  "max_sequence_length": !!int "131072"
  "client_spec":
    "class_name": "fireworks_client.FireworksNoThinkingClient"
    "args":
      "base_url": "https://api.fireworks.ai/inference/v1"
      "openai_model_name": "accounts/fireworks/models/deepseek-v3p2"
