"tokenizer_configs":
- "name": "qwen/qwen3.5-9b"
  "tokenizer_spec":
    "class_name": "helm.tokenizers.huggingface_tokenizer.HuggingFaceTokenizer"
    "args":
      "pretrained_model_name_or_path": "Qwen/Qwen3.5-9B"
  "end_of_text_token": "<|im_end|>"
  "prefix_token": "<|im_start|>"
- "name": "moonshot/kimi-k2p5"
  "tokenizer_spec":
    "class_name": "helm.tokenizers.huggingface_tokenizer.HuggingFaceTokenizer"
    "args":
      "pretrained_model_name_or_path": "Qwen/Qwen2.5-7B"
  "end_of_text_token": "<|im_end|>"
  "prefix_token": "<|im_start|>"
- "name": "deepseek3_2_tokenizer"
  "tokenizer_spec":
    "class_name": "helm.tokenizers.huggingface_tokenizer.HuggingFaceTokenizer"
    "args":
      "pretrained_model_name_or_path": "Qwen/Qwen2.5-7B"
  "end_of_text_token": "<|im_end|>"
  "prefix_token": "<|im_start|>"
